[build-dependencies]
fluent-zero-build = "0.1.4"
relm4-icons-build = "0.11.0"

[dependencies]
relm4-components = "0.11.0"
relm4-icons = "0.11.0"
report = {path = "../report"}
utils = {path = "../utils"}
tokio = "1.50.0"
notify-rust = "4.14.0"
fluent-zero = "0.1.4"
unic-langid = {version = "0.9.6", features = ["macros"]}
anyhow.workspace = true
futures-util.workspace = true
relm4.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zbus.workspace = true

[lib]
name = "gui"
path = "src/lib.rs"

[lints]
workspace = true

[package]
name = "gui"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
