// This code was autogenerated with `dbus-codegen-rust --crossroads`, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus_crossroads as crossroads;

pub trait OrgFreedesktopXinuxRelago {
}

#[derive(Debug)]
pub struct OrgFreedesktopXinuxRelagoNixError {
    pub log_file: String,
}

impl arg::AppendAll for OrgFreedesktopXinuxRelagoNixError {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.log_file, i);
    }
}

impl arg::ReadAll for OrgFreedesktopXinuxRelagoNixError {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopXinuxRelagoNixError {
            log_file: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopXinuxRelagoNixError {
    const NAME: &'static str = "NixError";
    const INTERFACE: &'static str = "org.freedesktop.problems.daemon";
}

pub fn register_org_freedesktop_xinux_relago<T>(cr: &mut crossroads::Crossroads) -> crossroads::IfaceToken<T>
where T: OrgFreedesktopXinuxRelago + Send + 'static
{
    cr.register("org.freedesktop.problems.daemon", |b| {
        b.signal::<(String,), _>("NixError", ("log_file",));
    })
}

impl OrgFreedesktopXinuxRelago for () {
    
}