name: Test CI

on: [push, pull_request]

jobs:
  test-flake:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Flake check x86_64-linux
        run: nix flake check --system x86_64-linux --show-trace
        
      - name: Flake check aarch-linux
        run: nix flake check --system aarch-linux --show-trace
        
      - name: Flake check x86_64-darwin
        run: nix flake check --system x86_64-darwin --show-trace
        

  test-project:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Build the project with Nix
        run: nix build . --show-trace

      - name: Run all cargo tests
        run: nix develop --command -- cargo test
